### PR TITLE
[DOCS] Add systemds overview image in the homepage

### PR DESCRIPTION
**Pull request by j143**
image

### CODE REVIEW

**Comment by j143** [comment]
cc @phaniarnab 
cc @Baunsgaard

Please provide comments regarding the modifications required.

**Comment by Baunsgaard** [comment]
It would be nice if the background is transparent, to enable dark mode. For me this image background make the webpage look bad.
also design wise (this is a thing everyone have their own opinion on) i don't 100 % like it, but i guess it is better than the previous.

**Comment by Baunsgaard** [comment]
on the left the R logo should not be there. since we are not using R , just an R Like syntax

**Comment by phaniarnab** [comment]
I agree. Please do not remove the gif. We need to fix that at some point, but removing that/replacing it with a static image is not something I would suggest.

**Pull request closed without merging**
