### PR TITLE
Gitpodify

### PR DESCRIPTION
**Pull request by j143**
Should I add gitpod configuration.

With this it will be faster to update, the website with ease.

Then the instructions would be clicking on the `gitpod` badge,
and do development as we would do on our PC.

cc @Baunsgaard

### CODE REVIEW

**Comment by Baunsgaard** [comment]
Why would this make it faster?
Does it automatically update the webpage when we push to master?
I was under the impression that it would be safer and better for us at the moment to not have such automation, since we 1. don't have all the resources in master branch to fully construct the webpage, 2. don't want to risk removing some of the resources missing. I am refereeing to for instance legacy documentation of previous versions.

**Comment by j143** [comment]
> Why would this make it faster?

Sometimes we may not be able to use our PC to update the website.
When we open the code by clicking on `open in gitpod` button, it will clone
the repo and does

```sh

npm install 
npm install -g gulp      
gem install jekyll      
gulp

```


> Does it automatically update the webpage when we push to master?

No. It does not affect our code in any way. It is only for developer convenience. 

> I was under the impression that it would be safer and better for us at the moment to not have such automation, since we 
> 
> 1. don't have all the resources in master branch to fully construct the webpage, 
> 2. don't want to risk removing some of the resources missing. I am refereeing to for instance legacy documentation of previous versions.

👍 .  I am good with this one.

**Comment by j143** [comment]
I promise not to automate any `code push` official repo's without everyone's consent. 😺

**Comment by j143** [comment]
I promise not to automate any `code push` official repo's without everyone's consent. 😺

**Comment by j143** [comment]
Hi @Baunsgaard , shall we add this. Personally I do development on gitpod.io . This one is easier than fireup on a personal laptop (mine 8GB ram).

Of course, for Java code I do on personal computer with IntelliJ.

**Comment by Baunsgaard** [comment]
if you use it go for it.

**Pull request merged**
